Added sanity checks and improved the program's output.

diff --git a/callgraph b/callgraph
--- a/callgraph
+++ b/callgraph
@@ -22,25 +22,46 @@
 # CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
+prog_name="callgraph"
+
 if [ $# -lt 1 ]; then
-  echo "Usage: `basename $0` executable [args...]"
-  exit 1
-else
-  FILE=$1
-  shift
+    echo "Usage: $prog_name EXECUTABLE [ARGS...]"
+    echo
+    echo "Example: $prog_name ~/bin/test-program foo 23"
+    exit 1
 fi
 
-TRACE="`mktemp -t callgraph.XXXXXXXXXX`" || exit
-GETFUNCS="`mktemp -t callgraph.XXXXXXXXXX`" || exit
+# Sanity checks.
+FILE=$1
+
+if [ ! -x $FILE ]; then
+    echo "$prog_name: Unable to find executable '$FILE'"
+    exit 1
+fi
+
+LANG="" gdb --eval-command=quit $FILE 2>&1 \
+    | grep -E '(no\ debugging\ symbols\ found|not\ in\ executable\ format)' 2>&1 > /dev/null
+if [ $? -eq 0 ]; then
+    echo -n "$prog_name: Can't print call graph for '$FILE' because it's not a "
+    echo "binary executable compiled with debugging symbols."
+    exit 1;
+fi
+
+shift
+
+# Set up temporary files.
+TRACE="`mktemp -t $prog_name.XXXXXXXXXX`" || exit
+GETFUNCS="`mktemp -t $prog_name.XXXXXXXXXX`" || exit
 trap 'rm -f -- "$TRACE" "$GETFUNCS"' EXIT
 trap 'trap - EXIT; rm -f -- "$TRACE" "$GETFUNCS"; exit 1' HUP INT QUIT TERM
 
+# Take control of GDB and print call graph.
 cat > $GETFUNCS <<EOF
 set height 0
 info functions
 EOF
 
-gdb --batch --command=$GETFUNCS $FILE | awk '
+gdb --batch --command=$GETFUNCS $FILE 2>/dev/null | awk '
 function get_func_name(str)
 {
   split(str, part, "(");
@@ -76,8 +97,7 @@ END {
 }
 ' > $TRACE
 
-gdb --batch --command=$TRACE --tty=/dev/null --args $FILE $@ | awk '
-
+gdb --batch --command=$TRACE --tty=/dev/null --args $FILE $@ 2>/dev/null | awk '
 function get_callee(s)
 {
   split(s, info, ",");
